export const TeamsData = [
  {
    currentName: "Philadelphia 76ers",
    names: ["Philadelphia 76ers", "Syracuse Nationals"],
    conference: "East",
    division: "Atlantic",
    periods: [
      { period: "2015–present", abr: "PHI", logo: "/logos/current/76ers.svg" },
      { period: "2009–2014", abr: "PHI", logo: "/logos/old/76ers3.svg" },
      { period: "1997–2008", abr: "PHI", logo: "/logos/old/76ers2.png" },
      { period: "1977–1996", abr: "PHI", logo: "/logos/old/76ers1.png" },
    ],
  },
  {
    currentName: "Boston Celtics",
    names: ["Boston Celtics"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "1996–present",
        abr: "BOS",
        logo: "/logos/current/celtics.svg",
      },
      { period: "1974–1995", abr: "BOS", logo: "/logos/old/celtics1.gif" },
    ],
  },
  {
    currentName: "Los Angeles Lakers",
    names: ["Los Angeles Lakers", "Minneapolis Lakers"],
    conference: "West",
    division: "Pacific",
    periods: [
      { period: "2001–present", abr: "LAL", logo: "/logos/current/lakers.svg" },
      { period: "1977–2000", abr: "LAL", logo: "/logos/old/lakers1.png" },
    ],
  },
  {
    currentName: "Golden State Warriors",
    names: [
      "Golden State Warriors",
      "San Francisco Warriors",
      "Philadelphia Warriors",
    ],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2019-present",
        abr: "GSW",
        logo: "/logos/current/warriors.svg",
      },
      { period: "2010-2018", abr: "GSW", logo: "/logos/old/warriors4.svg" },
      { period: "1997-2009", abr: "GSW", logo: "/logos/old/warriors3.png" },
      { period: "1989-1996", abr: "GSW", logo: "/logos/old/warriors2.gif" },
      { period: "1976-1988", abr: "GSW", logo: "/logos/old/warriors1.png" },
    ],
  },
  {
    currentName: "Miami Heat",
    names: ["Miami Heat"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "1999-present",
        abr: "MIA",
        logo: "/logos/current/heat.svg",
      },
      { period: "1988-1998", abr: "MIA", logo: "/logos/old/heat1.png" },
    ],
  },
  {
    currentName: "Chicago Bulls",
    names: ["Chicago Bulls"],
    conference: "East",
    division: "Central",
    periods: [
      { period: "1966–present", abr: "CHI", logo: "/logos/current/bulls.svg" },
    ],
  },
  {
    currentName: "San Antonio Spurs",
    names: ["San Antonio Spurs", "Dallas Chaparrals", "Texas Chaparrals"],
    conference: "West",
    division: "Southwest",
    periods: [
      { period: "2018–present", abr: "SAS", logo: "/logos/current/spurs.svg" },
      { period: "2002–2017", abr: "SAS", logo: "/logos/old/spurs3.svg" },
      { period: "1990–2001", abr: "SAS", logo: "/logos/old/spurs2.png" },
      { period: "1976–1989", abr: "SAS", logo: "/logos/old/spurs1.webp" },
    ],
  },
  {
    currentName: "Houston Rockets",
    names: ["Houston Rockets", "San Diego Rockets"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2019–present",
        abr: "HOU",
        logo: "/logos/current/rockets.svg",
      },
      { period: "2004–2018", abr: "HOU", logo: "/logos/old/rockets3.png" },
      { period: "1995–2003", abr: "HOU", logo: "/logos/old/rockets2.png" },
      { period: "1972–1994", abr: "HOU", logo: "/logos/old/rockets1.png" },
    ],
  },
  {
    currentName: "Dallas Mavericks",
    names: ["Dallas Mavericks"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2001–present",
        abr: "DAL",
        logo: "/logos/current/mavericks.svg",
      },
      { period: "1993–2000", abr: "DAL", logo: "/logos/old/mavericks2.svg" },
      { period: "1980–1992", abr: "DAL", logo: "/logos/old/mavericks1.webp" },
    ],
  },
  {
    currentName: "Toronto Raptors",
    names: ["Toronto Raptors"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "2020–present",
        abr: "TOR",
        logo: "/logos/current/raptors.svg",
      },
      { period: "2015–2019", abr: "TOR", logo: "/logos/old/raptors3.png" },
      { period: "2008–2015", abr: "TOR", logo: "/logos/old/raptors2.png" },
      { period: "1995–2007", abr: "TOR", logo: "/logos/old/raptors1.png" },
    ],
  },
  {
    currentName: "New York Knicks",
    names: ["New York Knicks"],
    conference: "East",
    division: "Atlantic",
    periods: [
      { period: "2011–present", abr: "NYK", logo: "/logos/current/knicks.svg" },
      { period: "1996–2011", abr: "NYK", logo: "/logos/old/knicks4.png" },
      { period: "1993–1995", abr: "NYK", logo: "/logos/old/knicks3.webp" },
      { period: "1990–1992", abr: "NYK", logo: "/logos/old/knicks2.png" },
      { period: "1984–1989", abr: "NYK", logo: "/logos/old/knicks1.webp" },
    ],
  },
  {
    currentName: "Brooklyn Nets",
    names: ["Brooklyn Nets", "New Jersey Nets"],
    conference: "East",
    division: "Atlantic",
    periods: [
      { period: "2013–present", abr: "BKN", logo: "/logos/current/nets.svg" },
      { period: "1997–2012", abr: "NJN", logo: "/logos/old/nets3.svg" },
      { period: "1990–1996", abr: "NJN", logo: "/logos/old/nets2.gif" },
      { period: "1979–1989", abr: "NJN", logo: "/logos/old/nets1.png" },
    ],
  },
  {
    currentName: "Los Angeles Clippers",
    names: ["Los Angeles Clippers", "San Diego Clippers", "Buffalo Braves"],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2025–present",
        abr: "LAC",
        logo: "/logos/current/clippers.svg",
      },
      { period: "2015–2024", abr: "LAC", logo: "/logos/old/clippers2.png" },
      { period: "1985–2014", abr: "LAC", logo: "/logos/old/clippers1.png" },
    ],
  },
  {
    currentName: "Atlanta Hawks",
    names: [
      "Atlanta Hawks",
      "St. Louis Hawks",
      "Milwaukee Hawks",
      "Tri-Cities Blackhawks",
    ],
    conference: "East",
    division: "Southeast",
    periods: [
      { period: "2021–present", abr: "ATL", logo: "/logos/current/hawks.svg" },
      { period: "2016–2020", abr: "ATL", logo: "/logos/old/hawks4.svg" },
      { period: "2008–2015", abr: "ATL", logo: "/logos/old/hawks3.png" },
      { period: "1996–2007", abr: "ATL", logo: "/logos/old/hawks2.webp" },
      { period: "1972–1995", abr: "ATL", logo: "/logos/old/hawks1.webp" },
    ],
  },
  {
    currentName: "Portland Trail Blazers",
    names: ["Portland Trail Blazers"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2017–present",
        abr: "POR",
        logo: "/logos/current/blazers.svg",
      },
      { period: "2004–2016", abr: "POR", logo: "/logos/old/blazers4.svg" },
      { period: "2002–2003", abr: "POR", logo: "/logos/old/blazers3.webp" },
      { period: "1990–2001", abr: "POR", logo: "/logos/old/blazers2.png" },
      { period: "1970–1989", abr: "POR", logo: "/logos/old/blazers1.webp" },
    ],
  },
  {
    currentName: "Utah Jazz",
    names: ["Utah Jazz", "New Orleans Jazz"],
    conference: "West",
    division: "Northwest",
    periods: [
      { period: "2023–present", abr: "UTA", logo: "/logos/current/jazz.svg" },
      { period: "2017–2022", abr: "UTA", logo: "/logos/old/jazz5.png" },
      { period: "2011–2016", abr: "UTA", logo: "/logos/old/jazz4.png" },
      { period: "2005–2010", abr: "UTA", logo: "/logos/old/jazz3.svg" },
      { period: "1997–2004", abr: "UTA", logo: "/logos/old/jazz2.png" },
      { period: "1979–1996", abr: "UTA", logo: "/logos/old/jazz1.png" },
    ],
  },
  {
    currentName: "Phoenix Suns",
    names: ["Phoenix Suns"],
    conference: "West",
    division: "Pacific",
    periods: [
      { period: "2013–present", abr: "PHX", logo: "/logos/current/suns.svg" },
      { period: "2000–2012", abr: "PHX", logo: "/logos/old/suns3.png" },
      { period: "1992–1999", abr: "PHX", logo: "/logos/old/suns2.webp" },
      { period: "1968–1991", abr: "PHX", logo: "/logos/old/suns1.png" },
    ],
  },
  {
    currentName: "Indiana Pacers",
    names: ["Indiana Pacers"],
    conference: "East",
    division: "Central",
    periods: [
      { period: "2017–present", abr: "IND", logo: "/logos/current/pacers.svg" },
      { period: "2005–2016", abr: "IND", logo: "/logos/old/pacers3.png" },
      { period: "1991–2004", abr: "IND", logo: "/logos/old/pacers2.webp" },
      { period: "1976–1990", abr: "IND", logo: "/logos/old/pacers1.webp" },
    ],
  },
  {
    currentName: "Oklahoma City Thunder",
    names: ["Oklahoma City Thunder", "Seattle SuperSonics"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2009–present",
        abr: "OKC",
        logo: "/logos/current/thunder.svg",
      },
      { period: "2001–2008", abr: "SEA", logo: "/logos/old/sonics3.svg" },
      { period: "1995–2000", abr: "SEA", logo: "/logos/old/sonics2.png" },
      { period: "1975–1994", abr: "SEA", logo: "/logos/old/sonics1.png" },
    ],
  },
  {
    currentName: "New Orleans Pelicans",
    names: [
      "New Orleans Pelicans",
      "New Orleans Hornets",
      "New Orleans/Oklahoma City Hornets",
    ],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2023–present",
        abr: "NOP",
        logo: "/logos/current/pelicans.svg",
      },
      { period: "2013–2022", abr: "NOP", logo: "/logos/old/pelicans3.png" },
      { period: "2008–2012", abr: "NOH", logo: "/logos/old/pelicans2.png" },
      { period: "1995-2007", abr: "NOH", logo: "/logos/old/pelicans1.gif" },
    ],
  },
  {
    currentName: "Minnesota Timberwolves",
    names: ["Minnesota Timberwolves"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2017–present",
        abr: "MIN",
        logo: "/logos/current/timberwolves.svg",
      },
      { period: "2009–2016", abr: "MIN", logo: "/logos/old/timberwolves3.png" },
      {
        period: "1997–2008",
        abr: "MIN",
        logo: "/logos/old/timberwolves2.webp",
      },
      { period: "1990–1996", abr: "MIN", logo: "/logos/old/timberwolves1.png" },
    ],
  },
  {
    currentName: "Sacramento Kings",
    names: [
      "Sacramento Kings",
      "Kansas City Kings",
      "Kansas City–Omaha Kings",
      "Cincinnati Royals",
      "Rochester Royals",
    ],
    conference: "West",
    division: "Pacific",
    periods: [
      { period: "2016–present", abr: "SAC", logo: "/logos/current/kings.svg" },
      { period: "1994–2015", abr: "SAC", logo: "/logos/old/kings3.png" },
      { period: "1985–1993", abr: "SAC", logo: "/logos/old/kings2.webp" },
      { period: "1976–1984", abr: "KCK", logo: "/logos/old/kings1.png" },
    ],
  },
  {
    currentName: "Detroit Pistons",
    names: ["Detroit Pistons", "Fort Wayne Pistons"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2017–present",
        abr: "DET",
        logo: "/logos/current/pistons.svg",
      },
      { period: "2005–2016", abr: "DET", logo: "/logos/old/pistons4.png" },
      { period: "2001–2004", abr: "DET", logo: "/logos/old/pistons3.webp" },
      { period: "1996–2000", abr: "DET", logo: "/logos/old/pistons2.webp" },
      { period: "1979–1995", abr: "DET", logo: "/logos/old/pistons1.png" },
    ],
  },
  {
    currentName: "Charlotte Hornets",
    names: ["Charlotte Hornets", "Charlotte Bobcats"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2015–present",
        abr: "CHA",
        logo: "/logos/current/hornets.svg",
      },
      { period: "2012–2014", abr: "CHB", logo: "/logos/old/hornets3.png" },
      { period: "2004–2011", abr: "CHB", logo: "/logos/old/hornets2.png" },
      { period: "1989–2002", abr: "CHA", logo: "/logos/old/hornets1.png" },
    ],
  },
  {
    currentName: "Washington Wizards",
    names: ["Washington Wizards", "Washington Bullets"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2015–present",
        abr: "WAS",
        logo: "/logos/current/wizards.svg",
      },
      { period: "2011–2014", abr: "WAS", logo: "/logos/old/wizards4.png" },
      { period: "1998–2010", abr: "WAS", logo: "/logos/old/wizards3.png" },
      { period: "1987–1997", abr: "WSB", logo: "/logos/old/wizards2.gif" },
      { period: "1974–1986", abr: "WSB", logo: "/logos/old/wizards1.png" },
    ],
  },
  {
    currentName: "Orlando Magic",
    names: ["Orlando Magic"],
    conference: "East",
    division: "Southeast",
    periods: [
      { period: "2026–present", abr: "ORL", logo: "/logos/current/magic.svg" },
      { period: "2011–2025", abr: "ORL", logo: "/logos/old/magic3.svg" },
      { period: "2001–2010", abr: "ORL", logo: "/logos/old/magic2.png" },
      { period: "1989–2000", abr: "ORL", logo: "/logos/old/magic1.png" },
    ],
  },
  {
    currentName: "Memphis Grizzlies",
    names: ["Memphis Grizzlies", "Vancouver Grizzlies"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2018–present",
        abr: "MEM",
        logo: "/logos/current/grizzlies.svg",
      },
      { period: "2004–2017", abr: "MEM", logo: "/logos/old/grizzlies3.png" },
      { period: "2002–2003", abr: "MEM", logo: "/logos/old/grizzlies2.png" },
      { period: "1995–2001", abr: "VAN", logo: "/logos/old/grizzlies1.png" },
    ],
  },
  {
    currentName: "Denver Nuggets",
    names: ["Denver Nuggets", "Denver Rockets"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2019–present",
        abr: "DEN",
        logo: "/logos/current/nuggets.svg",
      },
      { period: "2008–2018", abr: "DEN", logo: "/logos/old/nuggets4.svg" },
      { period: "2004–2007", abr: "DEN", logo: "/logos/old/nuggets3.png" },
      { period: "1994–2003", abr: "DEN", logo: "/logos/old/nuggets2.webp" },
      { period: "1982–1993", abr: "DEN", logo: "/logos/old/nuggets1.png" },
    ],
  },
  {
    currentName: "Cleveland Cavaliers",
    names: ["Cleveland Cavaliers"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2022–present",
        abr: "CLE",
        logo: "/logos/current/cavaliers.svg",
      },
      { period: "2017–2021", abr: "CLE", logo: "/logos/old/cavaliers5.png" },
      { period: "2010–2016", abr: "CLE", logo: "/logos/old/cavaliers4.svg" },
      { period: "2003–2009", abr: "CLE", logo: "/logos/old/cavaliers3.png" },
      { period: "1994–2002", abr: "CLE", logo: "/logos/old/cavaliers2.png" },
      { period: "1983–1993", abr: "CLE", logo: "/logos/old/cavaliers1.png" },
    ],
  },
  {
    currentName: "Milwaukee Bucks",
    names: ["Milwaukee Bucks"],
    conference: "East",
    division: "Central",
    periods: [
      { period: "2015–present", abr: "MIL", logo: "/logos/current/bucks.svg" },
      { period: "2007–2014", abr: "MIL", logo: "/logos/old/bucks3.png" },
      { period: "1994–2006", abr: "MIL", logo: "/logos/old/bucks2.webp" },
      { period: "1968–1993", abr: "MIL", logo: "/logos/old/bucks1.webp" },
    ],
  },
];
