export const TeamLogos = [
  {
    team: "Philadelphia 76ers",
    abr: "PHI",
    logo: "/logos/current/76ers.svg",
    period: "2015–present",
  },
  {
    team: "Boston Celtics",
    abr: "BOS",
    logo: "/logos/current/celtics.svg",
    period: "1978–present",
  },
  {
    team: "Los Angeles Lakers",
    abr: "LAL",
    logo: "/logos/current/lakers.svg",
    period: "2001–present",
  },
  {
    team: "Golden State Warriors",
    abr: "GSW",
    logo: "/logos/current/warriors.svg",
    period: "2010–present",
  },
  {
    team: "Miami Heat",
    abr: "MIA",
    logo: "/logos/current/heat.svg",
    period: "1999–present",
  },
  {
    team: "Chicago Bulls",
    abr: "CHI",
    logo: "/logos/current/bulls.svg",
    period: "1966–present",
  },
  {
    team: "San Antonio Spurs",
    abr: "SAS",
    logo: "/logos/current/spurs.svg",
    period: "2002–present",
  },
  {
    team: "Houston Rockets",
    abr: "HOU",
    logo: "/logos/current/rockets.svg",
    period: "2003–present",
  },
  {
    team: "Dallas Mavericks",
    abr: "DAL",
    logo: "/logos/current/mavericks.svg",
    period: "2001–present",
  },
  {
    team: "Toronto Raptors",
    abr: "TOR",
    logo: "/logos/current/raptors.svg",
    period: "2015–present",
  },
  {
    team: "New York Knicks",
    abr: "NYK",
    logo: "/logos/current/knicks.svg",
    period: "1992–present",
  },
  {
    team: "Brooklyn Nets",
    abr: "BKN",
    logo: "/logos/current/nets.svg",
    period: "2012–present",
  },
  {
    team: "Los Angeles Clippers",
    abr: "LAC",
    logo: "/logos/current/clippers.svg",
    period: "2025–present",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/current/hawks.svg",
    period: "2015–present",
  },
  {
    team: "Portland Trail Blazers",
    abr: "POR",
    logo: "/logos/current/blazers.svg",
    period: "2002–present",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/current/jazz.svg",
    period: "2016–present",
  },
  {
    team: "Phoenix Suns",
    abr: "PHX",
    logo: "/logos/current/suns.svg",
    period: "2013–present",
  },
  {
    team: "Indiana Pacers",
    abr: "IND",
    logo: "/logos/current/pacers.svg",
    period: "1997–present",
  },
  {
    team: "Oklahoma City Thunder",
    abr: "OKC",
    logo: "/logos/current/thunder.svg",
    period: "2008–present",
  },
  {
    team: "New Orleans Pelicans",
    abr: "NOP",
    logo: "/logos/current/pelicans.svg",
    period: "2013–present",
  },
  {
    team: "Minnesota Timberwolves",
    abr: "MIN",
    logo: "/logos/current/timberwolves.svg",
    period: "2008–present",
  },
  {
    team: "Sacramento Kings",
    abr: "SAC",
    logo: "/logos/current/kings.svg",
    period: "2022–present",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/current/pistons.svg",
    period: "2017–present",
  },
  {
    team: "Charlotte Hornets",
    abr: "CHA",
    logo: "/logos/current/hornets.svg",
    period: "2004–present",
  },
  {
    team: "Washington Wizards",
    abr: "WAS",
    logo: "/logos/current/wizards.svg",
    period: "2011–present",
  },
  {
    team: "Orlando Magic",
    abr: "ORL",
    logo: "/logos/current/magic.svg",
    period: "2015–present",
  },
  {
    team: "Memphis Grizzlies",
    abr: "MEM",
    logo: "/logos/current/grizzlies.svg",
    period: "2022–present",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/current/nuggets.svg",
    period: "2018–present",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/current/cavaliers.svg",
    period: "2017–present",
  },
  {
    team: "Milwaukee Bucks",
    abr: "MIL",
    logo: "/logos/current/bucks.svg",
    period: "2015–present",
  },
];
