export const TeamLogos = [
  {
    team: "Philadelphia 76ers",
    abr: "PHI",
    logo: "/logos/current/76ers.svg",
    period: "2015–present",
  },
  {
    team: "Philadelphia 76ers",
    abr: "PHI",
    logo: "/logos/old/76ers3.svg",
    period: "2009-2014",
  },
  {
    team: "Philadelphia 76ers",
    abr: "PHI",
    logo: "/logos/old/76ers2.png",
    period: "1997-2008",
  },
  {
    team: "Philadelphia 76ers",
    abr: "PHI",
    logo: "/logos/old/76ers1.png",
    period: "1977-1996",
  },
  {
    team: "Boston Celtics",
    abr: "BOS",
    logo: "/logos/current/celtics.svg",
    period: "1996-present",
  },
  {
    team: "Boston Celtics",
    abr: "BOS",
    logo: "/logos/old/celtics1.png",
    period: "1974-1995",
  },
  {
    team: "Los Angeles Lakers",
    abr: "LAL",
    logo: "/logos/current/lakers.svg",
    period: "2001–present",
  },
  {
    team: "Los Angeles Lakers",
    abr: "LAL",
    logo: "/logos/old/lakers1.png",
    period: "1977-2000",
  },
  {
    team: "Golden State Warriors",
    abr: "GSW",
    logo: "/logos/current/warriors.svg",
    period: "2019–present",
  },
  {
    team: "Golden State Warriors",
    abr: "GSW",
    logo: "/logos/old/warriors3.svg",
    period: "2010-2018",
  },
  {
    team: "Golden State Warriors",
    abr: "GSW",
    logo: "/logos/old/warriors2.png",
    period: "1997-2009",
  },
  {
    team: "Golden State Warriors",
    abr: "GSW",
    logo: "/logos/old/warriors1.gif",
    period: "1988-1996",
  },
  {
    team: "Miami Heat",
    abr: "MIA",
    logo: "/logos/current/heat.svg",
    period: "1999–present",
  },
  {
    team: "Miami Heat",
    abr: "MIA",
    logo: "/logos/old/heat1.png",
    period: "1988-1998",
  },
  {
    team: "Chicago Bulls",
    abr: "CHI",
    logo: "/logos/current/bulls.svg",
    period: "1966–present",
  },
  {
    team: "San Antonio Spurs",
    abr: "SAS",
    logo: "/logos/current/spurs.svg",
    period: "2018-present",
  },
  {
    team: "San Antonio Spurs",
    abr: "SAS",
    logo: "/logos/old/spurs2.svg",
    period: "2002-2017",
  },
  {
    team: "San Antonio Spurs",
    abr: "SAS",
    logo: "/logos/old/spurs1.png",
    period: "1990-2001",
  },
  {
    team: "Houston Rockets",
    abr: "HOU",
    logo: "/logos/current/rockets.svg",
    period: "2019-present",
  },
  {
    team: "Houston Rockets",
    abr: "HOU",
    logo: "/logos/old/rockets3.png",
    period: "2004-2018",
  },
  {
    team: "Houston Rockets",
    abr: "HOU",
    logo: "/logos/old/rockets2.png",
    period: "1995-2003",
  },
  {
    team: "Houston Rockets",
    abr: "HOU",
    logo: "/logos/old/rockets1.png",
    period: "1972-1994",
  },
  {
    team: "Dallas Mavericks",
    abr: "DAL",
    logo: "/logos/current/mavericks.svg",
    period: "2001–present",
  },
  {
    team: "Dallas Mavericks",
    abr: "DAL",
    logo: "/logos/old/mavericks2.svg",
    period: "1993-2000",
  },
  {
    team: "Dallas Mavericks",
    abr: "DAL",
    logo: "/logos/old/mavericks1.webp",
    period: "1980-1992",
  },
  {
    team: "Toronto Raptors",
    abr: "TOR",
    logo: "/logos/current/raptors.svg",
    period: "2020-present",
  },
  {
    team: "Toronto Raptors",
    abr: "TOR",
    logo: "/logos/old/raptors3.png",
    period: "2015-2019",
  },
  {
    team: "Toronto Raptors",
    abr: "TOR",
    logo: "/logos/old/raptors2.png",
    period: "2008-2015",
  },
  {
    team: "Toronto Raptors",
    abr: "TOR",
    logo: "/logos/old/raptors1.png",
    period: "1995-2007",
  },
  {
    team: "New York Knicks",
    abr: "NYK",
    logo: "/logos/current/knicks.svg",
    period: "2011-present",
  },
  {
    team: "New York Knicks",
    abr: "NYK",
    logo: "/logos/old/knicks3.avif",
    period: "1996-2011",
  },
  {
    team: "New York Knicks",
    abr: "NYK",
    logo: "/logos/old/knicks2.webp",
    period: "1993-1995",
  },
  {
    team: "New York Knicks",
    abr: "NYK",
    logo: "/logos/old/knicks1.png",
    period: "1990-1992",
  },
  {
    team: "Brooklyn Nets",
    abr: "BKN",
    logo: "/logos/current/nets.svg",
    period: "2012–present",
  },
  {
    team: "New Jersey Nets",
    abr: "NJN",
    logo: "/logos/old/nets2.svg",
    period: "1997-2011",
  },
  {
    team: "New Jersey Nets",
    abr: "NJN",
    logo: "/logos/old/nets1.gif",
    period: "1990-1996",
  },
  {
    team: "Los Angeles Clippers",
    abr: "LAC",
    logo: "/logos/current/clippers.svg",
    period: "2025–present",
  },
  {
    team: "Los Angeles Clippers",
    abr: "LAC",
    logo: "/logos/old/clippers2.png",
    period: "2015-2024",
  },
  {
    team: "Los Angeles Clippers",
    abr: "LAC",
    logo: "/logos/old/clippers1.png",
    period: "1985-2014",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/current/hawks.svg",
    period: "2021-present",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/old/hawks4.svg",
    period: "2016-2020",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/old/hawks3.png",
    period: "2008-2015",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/old/hawks2.webp",
    period: "1996-2007",
  },
  {
    team: "Atlanta Hawks",
    abr: "ATL",
    logo: "/logos/old/hawks1.webp",
    period: "1972-1995",
  },
  {
    team: "Portland Trail Blazers",
    abr: "POR",
    logo: "/logos/current/blazers.svg",
    period: "2017-present",
  },
  {
    team: "Portland Trail Blazers",
    abr: "POR",
    logo: "/logos/old/blazers3.svg",
    period: "2004-2016",
  },
  {
    team: "Portland Trail Blazers",
    abr: "POR",
    logo: "/logos/old/blazers2.webp",
    period: "2002-2003",
  },
  {
    team: "Portland Trail Blazers",
    abr: "POR",
    logo: "/logos/old/blazers1.png",
    period: "1990-2001",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/current/jazz.svg",
    period: "2023-present",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/old/jazz5.png",
    period: "2017-2022",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/old/jazz4.png",
    period: "2011-2016",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/old/jazz3.svg",
    period: "2005-2010",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/old/jazz2.png",
    period: "1997-2004",
  },
  {
    team: "Utah Jazz",
    abr: "UTA",
    logo: "/logos/old/jazz1.png",
    period: "1979-1996",
  },
  {
    team: "Phoenix Suns",
    abr: "PHX",
    logo: "/logos/current/suns.svg",
    period: "2013–present",
  },
  {
    team: "Phoenix Suns",
    abr: "PHX",
    logo: "/logos/old/suns3.png",
    period: "2000-2012",
  },
  {
    team: "Phoenix Suns",
    abr: "PHX",
    logo: "/logos/old/suns2.webp",
    period: "1992-1999",
  },
  {
    team: "Phoenix Suns",
    abr: "PHX",
    logo: "/logos/old/suns1.png",
    period: "1968-1991",
  },
  {
    team: "Indiana Pacers",
    abr: "IND",
    logo: "/logos/current/pacers.svg",
    period: "2017–present",
  },
  {
    team: "Indiana Pacers",
    abr: "IND",
    logo: "/logos/old/pacers2.png",
    period: "2005-2016",
  },
  {
    team: "Indiana Pacers",
    abr: "IND",
    logo: "/logos/old/pacers1.webp",
    period: "1990-2004",
  },
  {
    team: "Oklahoma City Thunder",
    abr: "OKC",
    logo: "/logos/current/thunder.svg",
    period: "2009–present",
  },
  {
    team: "Seattle SuperSonics",
    abr: "SEA",
    logo: "/logos/old/sonics3.svg",
    period: "2001-2008",
  },
  {
    team: "Seattle SuperSonics",
    abr: "SEA",
    logo: "/logos/old/sonics2.png",
    period: "1995-2000",
  },
  {
    team: "Seattle SuperSonics",
    abr: "SEA",
    logo: "/logos/old/sonics1.png",
    period: "1975-1994",
  },
  {
    team: "New Orleans Pelicans",
    abr: "NOP",
    logo: "/logos/current/pelicans.svg",
    period: "2023–present",
  },
  {
    team: "New Orleans Pelicans",
    abr: "NOP",
    logo: "/logos/old/pelicans3.png",
    period: "2013-2022",
  },
  {
    team: "New Orleans Hornets",
    abr: "NOH",
    logo: "/logos/old/pelicans2.webp",
    period: "2008-2012",
  },
  {
    team: "New Orleans Hornets",
    abr: "NOH",
    logo: "/logos/old/pelicans1.png",
    period: "2002-2007",
  },
  {
    team: "Minnesota Timberwolves",
    abr: "MIN",
    logo: "/logos/current/timberwolves.svg",
    period: "2017–present",
  },
  {
    team: "Minnesota Timberwolves",
    abr: "MIN",
    logo: "/logos/old/timberwolves3.png",
    period: "2009-2016",
  },
  {
    team: "Minnesota Timberwolves",
    abr: "MIN",
    logo: "/logos/old/timberwolves2.webp",
    period: "1997-2008",
  },
  {
    team: "Minnesota Timberwolves",
    abr: "MIN",
    logo: "/logos/old/timberwolves1.png",
    period: "1990-1996",
  },
  {
    team: "Sacramento Kings",
    abr: "SAC",
    logo: "/logos/current/kings.svg",
    period: "2016–present",
  },
  {
    team: "Sacramento Kings",
    abr: "SAC",
    logo: "/logos/old/kings2.png",
    period: "1994-2015",
  },
  {
    team: "Sacramento Kings",
    abr: "SAC",
    logo: "/logos/old/kings1.webp",
    period: "1986-1993",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/current/pistons.svg",
    period: "2017–present",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/old/pistons4.png",
    period: "2005-2016",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/old/pistons3.webp",
    period: "2001-2004",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/old/pistons2.webp",
    period: "1996-2000",
  },
  {
    team: "Detroit Pistons",
    abr: "DET",
    logo: "/logos/old/pistons1.png",
    period: "1979-1995",
  },
  {
    team: "Charlotte Hornets",
    abr: "CHA",
    logo: "/logos/current/hornets.svg",
    period: "2015-present",
  },
  {
    team: "Charlotte Bobcats",
    abr: "CHB",
    logo: "/logos/old/hornets3.png",
    period: "2012-2014",
  },
  {
    team: "Charlotte Bobcats",
    abr: "CHB",
    logo: "/logos/old/hornets2.png",
    period: "2004-2011",
  },
  {
    team: "Charlotte Hornets",
    abr: "CHA",
    logo: "/logos/old/hornets1.png",
    period: "1989-2002",
  },
  {
    team: "Washington Wizards",
    abr: "WAS",
    logo: "/logos/current/wizards.svg",
    period: "2015-present",
  },
  {
    team: "Washington Wizards",
    abr: "WAS",
    logo: "/logos/old/wizards3.png",
    period: "2011-2014",
  },
  {
    team: "Washington Wizards",
    abr: "WAS",
    logo: "/logos/old/wizards2.png",
    period: "1997-2010",
  },
  {
    team: "Washington Bullets",
    abr: "WSB",
    logo: "/logos/old/wizards1.gif",
    period: "1987-1996",
  },
  {
    team: "Orlando Magic",
    abr: "ORL",
    logo: "/logos/current/magic.svg",
    period: "2026-present",
  },
  {
    team: "Orlando Magic",
    abr: "ORL",
    logo: "/logos/old/magic3.svg",
    period: "2011-2025",
  },
  {
    team: "Orlando Magic",
    abr: "ORL",
    logo: "/logos/old/magic2.png",
    period: "2001-2010",
  },
  {
    team: "Orlando Magic",
    abr: "ORL",
    logo: "/logos/old/magic1.png",
    period: "1989-2000",
  },
  {
    team: "Memphis Grizzlies",
    abr: "MEM",
    logo: "/logos/current/grizzlies.svg",
    period: "2018-present",
  },
  {
    team: "Memphis Grizzlies",
    abr: "MEM",
    logo: "/logos/old/grizzlies3.png",
    period: "2004-2017",
  },
  {
    team: "Memphis Grizzlies",
    abr: "MEM",
    logo: "/logos/old/grizzlies2.png",
    period: "2002-2003",
  },
  {
    team: "Vancouver Grizzlies",
    abr: "VAN",
    logo: "/logos/old/grizzlies1.png",
    period: "1995-2001",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/current/nuggets.svg",
    period: "2019–present",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/old/nuggets4.svg",
    period: "2008-2018",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/old/nuggets3.png",
    period: "2004-2007",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/old/nuggets2.webp",
    period: "1994-2003",
  },
  {
    team: "Denver Nuggets",
    abr: "DEN",
    logo: "/logos/old/nuggets1.png",
    period: "1982-1993",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/current/cavaliers.svg",
    period: "2022-present",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/old/cavaliers5.png",
    period: "2017-2021",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/old/cavaliers4.svg",
    period: "2010-2016",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/old/cavaliers3.png",
    period: "2003-2009",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/old/cavaliers2.png",
    period: "1994-2002",
  },
  {
    team: "Cleveland Cavaliers",
    abr: "CLE",
    logo: "/logos/old/cavaliers1.png",
    period: "1983-1993",
  },
  {
    team: "Milwaukee Bucks",
    abr: "MIL",
    logo: "/logos/current/bucks.svg",
    period: "2015–present",
  },
  {
    team: "Milwaukee Bucks",
    abr: "MIL",
    logo: "/logos/old/bucks3.png",
    period: "2007-2014",
  },
  {
    team: "Milwaukee Bucks",
    abr: "MIL",
    logo: "/logos/old/bucks2.webp",
    period: "1994-2006",
  },
  {
    team: "Milwaukee Bucks",
    abr: "MIL",
    logo: "/logos/old/bucks1.webp",
    period: "1968-1993",
  },
];
