export const teams = [
  "Philadelphia 76ers",
  "Boston Celtics",
  "New York Knicks",
  "Toronto Raptors",
  "Brooklyn Nets",
  "Cleveland Cavaliers",
  "Chicago Bulls",
  "Indiana Pacers",
  "Detroit Pistons",
  "Milwaukee Bucks",
  "Washington Wizards",
  "Miami Heat",
  "Atlanta Hawks",
  "Charlotte Hornets",
  "Orlando Magic",
  "Los Angeles Lakers",
  "Golden State Warriors",
  "Los Angeles Clippers",
  "Sacramento Kings",
  "Phoenix Suns",
  "San Antonio Spurs",
  "Houston Rockets",
  "Dallas Mavericks",
  "Memphis Grizzlies",
  "New Orleans Pelicans",
  "Denver Nuggets",
  "Utah Jazz",
  "Minnesota Timberwolves",
  "Oklahoma City Thunder",
  "Portland Trail Blazers",
];
