export const TeamsData = [
  {
    currentName: "Philadelphia 76ers",
    names: ["Philadelphia 76ers", "Syracuse Nationals"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "2015–present",
        abr: "PHI",
        logo: "/logos/current/76ers.svg",
        mainColor: "#006BB6",
        accentColor: "#DB0032",
      },
      {
        period: "2009–2014",
        abr: "PHI",
        logo: "/logos/old/76ers3.svg",
        mainColor: "#006BB6",
        accentColor: "#ED174C",
      },
      {
        period: "1997–2008",
        abr: "PHI",
        logo: "/logos/old/76ers2.png",
        mainColor: "#040204",
        accentColor: "#B69962",
      },
      {
        period: "1977–1996",
        abr: "PHI",
        logo: "/logos/old/76ers1.png",
        mainColor: "#094698",
        accentColor: "#D50032",
      },
    ],
  },
  {
    currentName: "Boston Celtics",
    names: ["Boston Celtics"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "1996–present",
        abr: "BOS",
        logo: "/logos/current/celtics.svg",
        mainColor: "#007A33",
        accentColor: "#BA9653",
      },
      {
        period: "1974–1995",
        abr: "BOS",
        logo: "/logos/old/celtics1.gif",
        mainColor: "#007A33",
        accentColor: "#BA9653",
      },
    ],
  },
  {
    currentName: "Los Angeles Lakers",
    names: ["Los Angeles Lakers", "Minneapolis Lakers"],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2001–present",
        abr: "LAL",
        logo: "/logos/current/lakers.svg",
        mainColor: "#552583",
        accentColor: "#FDB927",
      },
      {
        period: "1977–2000",
        abr: "LAL",
        logo: "/logos/old/lakers1.png",
        mainColor: "#552583",
        accentColor: "#FDB927",
      },
    ],
  },
  {
    currentName: "Golden State Warriors",
    names: [
      "Golden State Warriors",
      "San Francisco Warriors",
      "Philadelphia Warriors",
    ],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2019-present",
        abr: "GSW",
        logo: "/logos/current/warriors.svg",
        mainColor: "#1D428A",
        accentColor: "#FFC72C",
      },
      {
        period: "2010-2018",
        abr: "GSW",
        logo: "/logos/old/warriors4.svg",
        mainColor: "#1D428A",
        accentColor: "#FFC72C",
      },
      {
        period: "1997-2009",
        abr: "GSW",
        logo: "/logos/old/warriors3.png",
        mainColor: "#041E42",
        accentColor: "#FFA300",
      },
      {
        period: "1989-1996",
        abr: "GSW",
        logo: "/logos/old/warriors2.gif",
        mainColor: "#002F6C",
        accentColor: "#FFCD00",
      },
      {
        period: "1976-1988",
        abr: "GSW",
        logo: "/logos/old/warriors1.png",
        mainColor: "#002F6C",
        accentColor: "#FFCD00",
      },
    ],
  },
  {
    currentName: "Miami Heat",
    names: ["Miami Heat"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "1999-present",
        abr: "MIA",
        logo: "/logos/current/heat.svg",
        mainColor: "#98002E",
        accentColor: "#000000",
      },
      {
        period: "1988-1998",
        abr: "MIA",
        logo: "/logos/old/heat1.png",
        mainColor: "#98002E",
        accentColor: "#F9A01B",
      },
    ],
  },
  {
    currentName: "Chicago Bulls",
    names: ["Chicago Bulls"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "1966–present",
        abr: "CHI",
        logo: "/logos/current/bulls.svg",
        mainColor: "#D2153A",
        accentColor: "#000000",
      },
    ],
  },
  {
    currentName: "San Antonio Spurs",
    names: ["San Antonio Spurs", "Dallas Chaparrals", "Texas Chaparrals"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2018–present",
        abr: "SAS",
        logo: "/logos/current/spurs.svg",
        mainColor: "#000000",
        accentColor: "#C4CED4",
      },
      {
        period: "2002–2017",
        abr: "SAS",
        logo: "/logos/old/spurs3.svg",
        mainColor: "#000000",
        accentColor: "#C4CED4",
      },
      {
        period: "1990–2001",
        abr: "SAS",
        logo: "/logos/old/spurs2.png",
        mainColor: "#000000",
        accentColor: "#EF426F",
      },
      {
        period: "1976–1989",
        abr: "SAS",
        logo: "/logos/old/spurs1.webp",
        mainColor: "#000000",
        accentColor: "#8a8d8f",
      },
    ],
  },
  {
    currentName: "Houston Rockets",
    names: ["Houston Rockets", "San Diego Rockets"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2019–present",
        abr: "HOU",
        logo: "/logos/current/rockets.svg",
        mainColor: "#CE1141",
        accentColor: "#000000",
      },
      {
        period: "2004–2018",
        abr: "HOU",
        logo: "/logos/old/rockets3.png",
        mainColor: "#CE1141",
        accentColor: "#000000",
      },
      {
        period: "1995–2003",
        abr: "HOU",
        logo: "/logos/old/rockets2.png",
        mainColor: "#041E42",
        accentColor: "#BA0C2F",
      },
      {
        period: "1972–1994",
        abr: "HOU",
        logo: "/logos/old/rockets1.png",
        mainColor: "#BA0C2F",
        accentColor: "#FFC72C",
      },
    ],
  },
  {
    currentName: "Dallas Mavericks",
    names: ["Dallas Mavericks"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2001–present",
        abr: "DAL",
        logo: "/logos/current/mavericks.svg",
        mainColor: "#00538C",
        accentColor: "#B8C4CA",
      },
      {
        period: "1993–2000",
        abr: "DAL",
        logo: "/logos/old/mavericks2.svg",
        mainColor: "#002855",
        accentColor: "#00843D",
      },
      {
        period: "1980–1992",
        abr: "DAL",
        logo: "/logos/old/mavericks1.webp",
        mainColor: "#002855",
        accentColor: "#00843D",
      },
    ],
  },
  {
    currentName: "Toronto Raptors",
    names: ["Toronto Raptors"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "2020–present",
        abr: "TOR",
        logo: "/logos/current/raptors.svg",
        mainColor: "#ce1141",
        accentColor: "#000000",
      },
      {
        period: "2015–2019",
        abr: "TOR",
        logo: "/logos/old/raptors3.png",
        mainColor: "#CE1141",
        accentColor: "#000000",
      },
      {
        period: "2008–2015",
        abr: "TOR",
        logo: "/logos/old/raptors2.png",
        mainColor: "#CE1141",
        accentColor: "#000000",
      },
      {
        period: "1995–2007",
        abr: "TOR",
        logo: "/logos/old/raptors1.png",
        mainColor: "#BA0C2F",
        accentColor: "#753BBD",
      },
    ],
  },
  {
    currentName: "New York Knicks",
    names: ["New York Knicks"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "2011–present",
        abr: "NYK",
        logo: "/logos/current/knicks.svg",
        mainColor: "#006BB6",
        accentColor: "#F58426",
      },
      {
        period: "1996–2011",
        abr: "NYK",
        logo: "/logos/old/knicks4.png",
        mainColor: "#F58426",
        accentColor: "#000000",
      },
      {
        period: "1993–1995",
        abr: "NYK",
        logo: "/logos/old/knicks3.webp",
        mainColor: "#0072CE",
        accentColor: "#FE5000",
      },
      {
        period: "1990–1992",
        abr: "NYK",
        logo: "/logos/old/knicks2.png",
        mainColor: "#006BB6",
        accentColor: "#F58426",
      },
      {
        period: "1984–1989",
        abr: "NYK",
        logo: "/logos/old/knicks1.webp",
        mainColor: "#006BB6",
        accentColor: "#F58426",
      },
    ],
  },
  {
    currentName: "Brooklyn Nets",
    names: ["Brooklyn Nets", "New Jersey Nets"],
    conference: "East",
    division: "Atlantic",
    periods: [
      {
        period: "2013–present",
        abr: "BKN",
        logo: "/logos/current/nets.svg",
        mainColor: "#000000",
        accentColor: "#FFFFFF",
      },
      {
        period: "1997–2012",
        abr: "NJN",
        logo: "/logos/old/nets3.svg",
        mainColor: "#002A60",
        accentColor: "#CD1041",
      },
      {
        period: "1990–1996",
        abr: "NJN",
        logo: "/logos/old/nets2.gif",
        mainColor: "#002A60",
        accentColor: "#CD1041",
      },
      {
        period: "1979–1989",
        abr: "NJN",
        logo: "/logos/old/nets1.png",
        mainColor: "#002A60",
        accentColor: "#CD1041",
      },
    ],
  },
  {
    currentName: "Los Angeles Clippers",
    names: ["Los Angeles Clippers", "San Diego Clippers", "Buffalo Braves"],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2025–present",
        abr: "LAC",
        logo: "/logos/current/clippers.svg",
        mainColor: "#c8102E",
        accentColor: "#1D428A",
      },
      {
        period: "2015–2024",
        abr: "LAC",
        logo: "/logos/old/clippers2.png",
        mainColor: "#C8102E",
        accentColor: "#1D428A",
      },
      {
        period: "1985–2014",
        abr: "LAC",
        logo: "/logos/old/clippers1.png",
        mainColor: "#c8102E",
        accentColor: "#1D428A",
      },
    ],
  },
  {
    currentName: "Atlanta Hawks",
    names: [
      "Atlanta Hawks",
      "St. Louis Hawks",
      "Milwaukee Hawks",
      "Tri-Cities Blackhawks",
    ],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2021–present",
        abr: "ATL",
        logo: "/logos/current/hawks.svg",
        mainColor: "#C8102E",
        accentColor: "#FFFFFF",
      },
      {
        period: "2016–2020",
        abr: "ATL",
        logo: "/logos/old/hawks4.svg",
        mainColor: "#C8102E",
        accentColor: "#FFFFFF",
      },
      {
        period: "2008–2015",
        abr: "ATL",
        logo: "/logos/old/hawks3.png",
        mainColor: "#082240",
        accentColor: "#C8102E",
      },
      {
        period: "1996–2007",
        abr: "ATL",
        logo: "/logos/old/hawks2.webp",
        mainColor: "#C8102E",
        accentColor: "#FFCD00",
      },
      {
        period: "1972–1995",
        abr: "ATL",
        logo: "/logos/old/hawks1.webp",
        mainColor: "#C8102E",
        accentColor: "#ffffff",
      },
    ],
  },
  {
    currentName: "Portland Trail Blazers",
    names: ["Portland Trail Blazers"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2017–present",
        abr: "POR",
        logo: "/logos/current/blazers.svg",
        mainColor: "#E03A3E",
        accentColor: "#000000",
      },
      {
        period: "2004–2016",
        abr: "POR",
        logo: "/logos/old/blazers4.svg",
        mainColor: "#E03A3E",
        accentColor: "#000000",
      },
      {
        period: "2002–2003",
        abr: "POR",
        logo: "/logos/old/blazers3.webp",
        mainColor: "#E03A3E",
        accentColor: "#000000",
      },
      {
        period: "1990–2001",
        abr: "POR",
        logo: "/logos/old/blazers2.png",
        mainColor: "#E03A3E",
        accentColor: "#000000",
      },
      {
        period: "1970–1989",
        abr: "POR",
        logo: "/logos/old/blazers1.webp",
        mainColor: "#E03A3E",
        accentColor: "#000000",
      },
    ],
  },
  {
    currentName: "Utah Jazz",
    names: ["Utah Jazz", "New Orleans Jazz"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2023–present",
        abr: "UTA",
        logo: "/logos/current/jazz.svg",
        mainColor: "#000000",
        accentColor: "#ffffff",
      },
      {
        period: "2017–2022",
        abr: "UTA",
        logo: "/logos/old/jazz5.png",
        mainColor: "#002B5C",
        accentColor: "#F9A01B",
      },
      {
        period: "2011–2016",
        abr: "UTA",
        logo: "/logos/old/jazz4.png",
        mainColor: "#002B5C",
        accentColor: "#F9A01B",
      },
      {
        period: "2005–2010",
        abr: "UTA",
        logo: "/logos/old/jazz3.svg",
        mainColor: "#00275D",
        accentColor: "#6CAEDF",
      },
      {
        period: "1997–2004",
        abr: "UTA",
        logo: "/logos/old/jazz2.png",
        mainColor: "#753BBD",
        accentColor: "#00B6E9",
      },
      {
        period: "1979–1996",
        abr: "UTA",
        logo: "/logos/old/jazz1.png",
        mainColor: "#5C2460",
        accentColor: "#F4BC23",
      },
    ],
  },
  {
    currentName: "Phoenix Suns",
    names: ["Phoenix Suns"],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2013–present",
        abr: "PHX",
        logo: "/logos/current/suns.svg",
        mainColor: "#1d1160",
        accentColor: "#E56020",
      },
      {
        period: "2000–2012",
        abr: "PHX",
        logo: "/logos/old/suns3.png",
        mainColor: "#5F259F",
        accentColor: "#FF6900",
      },
      {
        period: "1992–1999",
        abr: "PHX",
        logo: "/logos/old/suns2.webp",
        mainColor: "#5F259F",
        accentColor: "#FF6900",
      },
      {
        period: "1968–1991",
        abr: "PHX",
        logo: "/logos/old/suns1.png",
        mainColor: "#682C88",
        accentColor: "#E3532B",
      },
    ],
  },
  {
    currentName: "Indiana Pacers",
    names: ["Indiana Pacers"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2017–present",
        abr: "IND",
        logo: "/logos/current/pacers.svg",
        mainColor: "#002D62",
        accentColor: "#FDBB30",
      },
      {
        period: "2005–2016",
        abr: "IND",
        logo: "/logos/old/pacers3.png",
        mainColor: "#002D62",
        accentColor: "#FDBB30",
      },
      {
        period: "1991–2004",
        abr: "IND",
        logo: "/logos/old/pacers2.webp",
        mainColor: "#1E1E4B",
        accentColor: "#F7D425",
      },
      {
        period: "1976–1990",
        abr: "IND",
        logo: "/logos/old/pacers1.webp",
        mainColor: "#313391",
        accentColor: "#FCC422",
      },
    ],
  },
  {
    currentName: "Oklahoma City Thunder",
    names: ["Oklahoma City Thunder", "Seattle SuperSonics"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2009–present",
        abr: "OKC",
        logo: "/logos/current/thunder.svg",
        mainColor: "#007ac1",
        accentColor: "#ef3b24",
      },
      {
        period: "2001–2008",
        abr: "SEA",
        logo: "/logos/old/sonics3.svg",
        mainColor: "#006032",
        accentColor: "#FFC221",
      },
      {
        period: "1995–2000",
        abr: "SEA",
        logo: "/logos/old/sonics2.png",
        mainColor: "#003111",
        accentColor: "#940000",
      },
      {
        period: "1975–1994",
        abr: "SEA",
        logo: "/logos/old/sonics1.png",
        mainColor: "#005128",
        accentColor: "#FFD600",
      },
    ],
  },
  {
    currentName: "New Orleans Pelicans",
    names: [
      "New Orleans Pelicans",
      "New Orleans Hornets",
      "New Orleans/Oklahoma City Hornets",
    ],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2023–present",
        abr: "NOP",
        logo: "/logos/current/pelicans.svg",
        mainColor: "#001544",
        accentColor: "#C69E66",
      },
      {
        period: "2013–2022",
        abr: "NOP",
        logo: "/logos/old/pelicans3.png",
        mainColor: "#001544",
        accentColor: "#E31836",
      },
      {
        period: "2008–2012",
        abr: "NOH",
        logo: "/logos/old/pelicans2.png",
        mainColor: "#1B0862",
        accentColor: "#0090C8",
      },
      {
        period: "1995–2007",
        abr: "NOH",
        logo: "/logos/old/pelicans1.gif",
        mainColor: "#273997",
        accentColor: "#0093B2",
      },
    ],
  },
  {
    currentName: "Minnesota Timberwolves",
    names: ["Minnesota Timberwolves"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2017–present",
        abr: "MIN",
        logo: "/logos/current/timberwolves.svg",
        mainColor: "#0A233F",
        accentColor: "#216193",
      },
      {
        period: "2009–2016",
        abr: "MIN",
        logo: "/logos/old/timberwolves3.png",
        mainColor: "#00537F",
        accentColor: "#000000",
      },
      {
        period: "1997–2008",
        abr: "MIN",
        logo: "/logos/old/timberwolves2.webp",
        mainColor: "#000000",
        accentColor: "#39784C",
      },
      {
        period: "1990–1996",
        abr: "MIN",
        logo: "/logos/old/timberwolves1.png",
        mainColor: "#106AB7",
        accentColor: "#15A44B",
      },
    ],
  },
  {
    currentName: "Sacramento Kings",
    names: [
      "Sacramento Kings",
      "Kansas City Kings",
      "Kansas City–Omaha Kings",
      "Cincinnati Royals",
      "Rochester Royals",
    ],
    conference: "West",
    division: "Pacific",
    periods: [
      {
        period: "2016–present",
        abr: "SAC",
        logo: "/logos/current/kings.svg",
        mainColor: "#662986",
        accentColor: "#5B727A",
      },
      {
        period: "1994–2015",
        abr: "SAC",
        logo: "/logos/old/kings3.png",
        mainColor: "#794D9B",
        accentColor: "#000000",
      },
      {
        period: "1985–1993",
        abr: "SAC",
        logo: "/logos/old/kings2.webp",
        mainColor: "#005BAE",
        accentColor: "#CD144D",
      },
      {
        period: "1976–1984",
        abr: "KCK",
        logo: "/logos/old/kings1.png",
        mainColor: "#0057B0",
        accentColor: "#F02E17",
      },
    ],
  },
  {
    currentName: "Detroit Pistons",
    names: ["Detroit Pistons", "Fort Wayne Pistons"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2017–present",
        abr: "DET",
        logo: "/logos/current/pistons.svg",
        mainColor: "#FF073B",
        accentColor: "#0064C9",
      },
      {
        period: "2005–2016",
        abr: "DET",
        logo: "/logos/old/pistons4.png",
        mainColor: "#FF2938",
        accentColor: "#0053D2",
      },
      {
        period: "2001–2004",
        abr: "DET",
        logo: "/logos/old/pistons3.webp",
        mainColor: "#C8102E",
        accentColor: "#006BB6",
      },
      {
        period: "1996–2000",
        abr: "DET",
        logo: "/logos/old/pistons2.webp",
        mainColor: "#088991",
        accentColor: "#C63635",
      },
      {
        period: "1979–1995",
        abr: "DET",
        logo: "/logos/old/pistons1.png",
        mainColor: "#0B47A0",
        accentColor: "#D4122A",
      },
    ],
  },
  {
    currentName: "Charlotte Hornets",
    names: ["Charlotte Hornets", "Charlotte Bobcats"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2015–present",
        abr: "CHA",
        logo: "/logos/current/hornets.svg",
        mainColor: "#008898",
        accentColor: "#262A5D",
      },
      {
        period: "2012–2014",
        abr: "CHB",
        logo: "/logos/old/hornets3.png",
        mainColor: "#022A60",
        accentColor: "#A2A1A7",
      },
      {
        period: "2004–2011",
        abr: "CHB",
        logo: "/logos/old/hornets2.png",
        mainColor: "#345C89",
        accentColor: "#E0312B",
      },
      {
        period: "1989–2002",
        abr: "CHA",
        logo: "/logos/old/hornets1.png",
        mainColor: "#05798A",
        accentColor: "#250173",
      },
    ],
  },
  {
    currentName: "Washington Wizards",
    names: ["Washington Wizards", "Washington Bullets"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2015–present",
        abr: "WAS",
        logo: "/logos/current/wizards.svg",
        mainColor: "#1C2D5C",
        accentColor: "#C41D3C",
      },
      {
        period: "2011–2014",
        abr: "WAS",
        logo: "/logos/old/wizards4.png",
        mainColor: "#002C5C",
        accentColor: "#E21737",
      },
      {
        period: "1998–2010",
        abr: "WAS",
        logo: "/logos/old/wizards3.png",
        mainColor: "#024373",
        accentColor: "#B7976E",
      },
      {
        period: "1987–1997",
        abr: "WSB",
        logo: "/logos/old/wizards2.gif",
        mainColor: "#023F7B",
        accentColor: "#D52F3A",
      },
      {
        period: "1974–1986",
        abr: "WSB",
        logo: "/logos/old/wizards1.png",
        mainColor: "#00339F",
        accentColor: "#CD3000",
      },
    ],
  },
  {
    currentName: "Orlando Magic",
    names: ["Orlando Magic"],
    conference: "East",
    division: "Southeast",
    periods: [
      {
        period: "2026–present",
        abr: "ORL",
        logo: "/logos/current/magic.svg",
        mainColor: "#0050B6",
        accentColor: "#ffffff",
      },
      {
        period: "2011–2025",
        abr: "ORL",
        logo: "/logos/old/magic3.svg",
        mainColor: "#0050B6",
        accentColor: "#9C9FA0",
      },
      {
        period: "2001–2010",
        abr: "ORL",
        logo: "/logos/old/magic2.png",
        mainColor: "#1C4DA2",
        accentColor: "#8D8F96",
      },
      {
        period: "1989–2000",
        abr: "ORL",
        logo: "/logos/old/magic1.png",
        mainColor: "#1C4DA2",
        accentColor: "#8D8F96",
      },
    ],
  },
  {
    currentName: "Memphis Grizzlies",
    names: ["Memphis Grizzlies", "Vancouver Grizzlies"],
    conference: "West",
    division: "Southwest",
    periods: [
      {
        period: "2018–present",
        abr: "MEM",
        logo: "/logos/current/grizzlies.svg",
        mainColor: "#1B1C3B",
        accentColor: "#6679A2",
      },
      {
        period: "2004–2017",
        abr: "MEM",
        logo: "/logos/old/grizzlies3.png",
        mainColor: "#0E335D",
        accentColor: "#488ABC",
      },
      {
        period: "2002–2003",
        abr: "MEM",
        logo: "/logos/old/grizzlies2.png",
        mainColor: "#04ABAE",
        accentColor: "#B9764D",
      },
      {
        period: "1995–2001",
        abr: "VAN",
        logo: "/logos/old/grizzlies1.png",
        mainColor: "#16A5AB",
        accentColor: "#945B40",
      },
    ],
  },
  {
    currentName: "Denver Nuggets",
    names: ["Denver Nuggets", "Denver Rockets"],
    conference: "West",
    division: "Northwest",
    periods: [
      {
        period: "2019–present",
        abr: "DEN",
        logo: "/logos/current/nuggets.svg",
        mainColor: "#051C3E",
        accentColor: "#F9BC22",
      },
      {
        period: "2008–2018",
        abr: "DEN",
        logo: "/logos/old/nuggets4.svg",
        mainColor: "#082752",
        accentColor: "#F9B93A",
      },
      {
        period: "2004–2007",
        abr: "DEN",
        logo: "/logos/old/nuggets3.png",
        mainColor: "#2B9EDA",
        accentColor: "#F7C02E",
      },
      {
        period: "1994–2003",
        abr: "DEN",
        logo: "/logos/old/nuggets2.webp",
        mainColor: "#07395D",
        accentColor: "#BC8E53",
      },
      {
        period: "1982–1993",
        abr: "DEN",
        logo: "/logos/old/nuggets1.png",
        mainColor: "#0F1856",
        accentColor: "#FA6011",
      },
    ],
  },
  {
    currentName: "Cleveland Cavaliers",
    names: ["Cleveland Cavaliers"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2022–present",
        abr: "CLE",
        logo: "/logos/current/cavaliers.svg",
        mainColor: "#77223E",
        accentColor: "#B9994C",
      },
      {
        period: "2017–2021",
        abr: "CLE",
        logo: "/logos/old/cavaliers5.png",
        mainColor: "#7E0628",
        accentColor: "#F8BF28",
      },
      {
        period: "2010–2016",
        abr: "CLE",
        logo: "/logos/old/cavaliers4.svg",
        mainColor: "#7F0031",
        accentColor: "#F8BF28",
      },
      {
        period: "2003–2009",
        abr: "CLE",
        logo: "/logos/old/cavaliers3.png",
        mainColor: "#05085D",
        accentColor: "#CD002B",
      },
      {
        period: "1994–2002",
        abr: "CLE",
        logo: "/logos/old/cavaliers2.png",
        mainColor: "#070100",
        accentColor: "#FF571F",
      },
      {
        period: "1983–1993",
        abr: "CLE",
        logo: "/logos/old/cavaliers1.png",
        mainColor: "#0A125D",
        accentColor: "#FF3832",
      },
    ],
  },
  {
    currentName: "Milwaukee Bucks",
    names: ["Milwaukee Bucks"],
    conference: "East",
    division: "Central",
    periods: [
      {
        period: "2015–present",
        abr: "MIL",
        logo: "/logos/current/bucks.svg",
        mainColor: "#264F37",
        accentColor: "#E1D3AE",
      },
      {
        period: "2007–2014",
        abr: "MIL",
        logo: "/logos/old/bucks3.png",
        mainColor: "#304B3B",
        accentColor: "#AC1A2F",
      },
      {
        period: "1994–2006",
        abr: "MIL",
        logo: "/logos/old/bucks2.webp",
        mainColor: "#064419",
        accentColor: "#5D378A",
      },
      {
        period: "1968–1993",
        abr: "MIL",
        logo: "/logos/old/bucks1.webp",
        mainColor: "#00982D",
        accentColor: "#F5A800",
      },
    ],
  },
];
